### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by Aravind-shrenivas** [INFO-523-Exercises/project-final-MineCrafters#2]
The following is the peer review of the project proposal by **Feature Finders Club** . The team members that participated in this review are 

- Eshaan Mathakari  - @eshaanmathakari
- Sanjay Bhargav Siddi - @sanjaybhargavsiddi
- Likith Kumar Dundigalla - @LikithKumarDundigalla
- Aravind shrenivas Murali - @Aravind-shrenivas
- Vamsi Vadala - @Vamsi-Vadala

- Describe the goal of the project.
What we understood from the abstract is that you are creating a system called 'SoleMate,' which will use machine learning algorithms to assist people in finding the ideal pair of shoes by considering various factors such as their favourite shoe brand, price, lifestyle, and personal fashion preferences.

- Describe the data used or collected.
The dataset comprises information related to products from Nike and Adidas, with a primary focus on shoes. It includes essential features such as product names, unique product IDs, listing prices, discounted sales prices, discount percentages, brand identifiers (Nike or Adidas), product descriptions, user-provided ratings (out of 5), the number of user reviews, and timestamps indicating the last customer visit to a product.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The main goal of the project is to develop a shoe-recommendation system called "SoleMate" that will revolutionise the way consumers select their shoes. This machine learning-based approach will provide personalised recommendations for a more seamless and customised purchasing experience in response to the subjective nature of shoe selection, which is influenced by brand, price, lifestyle, and fashion preferences. SoleMate uses machine learning algorithms to take a variety of aspects into account and provide users with customised shoe recommendations

- Is there anything that is unclear from the proposal?
1) The question "How do you find the perfect Solemate?"  is not close to the project, since you mentioned you are shoe recommending system and you named your system as "Solemate". It was not clear how can you find a perfect system whereas you want a perfect shoe.
2) "Visualising the favourite shoe brand based on the customer rating and the number of reviews "- Are you'll tackling the discrepancies too in that case? like there is a chance of fake reviews too, is that also being considered
3) " Create additional features if necessary, such as sentiment analysis scores for customer reviews"- In what case is this for? and also how can you take number as a sentiment please explain this?

- Provide constructive feedback on how the team might be able to improve their project.
1. While the high-level goal is evident, specifying more concrete objectives regarding the features to be used in the recommendation system would add clarity. Define the specific features you plan to leverage for more targeted results.
2. In the exploratory data analysis (EDA), consider a more in-depth explanation.  For example, you can investigate the distribution of ratings, discount percentages, and their impact on sales. Visualising correlations between different features could provide more insights.
3. Provide a bit more detail on why specific recommendation algorithms (collaborative filtering, content-based filtering, hybrid methods) were chosen. How do they align with the characteristics of the dataset and the goals of the project?

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
Accuracy score of the shoe recommendation system.

- Provide constructive feedback on any issues with file and/or code organisation.
No issues.

- (Optional) Any further comments or feedback?
Good luck!

**Comment by partha-pkp** [comment]
Thanks for the review!

**Comment by Syedaslamsheikdawood** [comment]
We made changes accordingly. Thank you!
