### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by Rohit-Hemaraja** [INFO-523-Exercises/project-final-MineCrafters#3]
The following is the peer review of the project proposal by The Null Wranglers. The team members that participated in this review are
Dong Chen - @dongchen18
Anjani Sowmya Bollapragada - @asbollapragada
Kristi Manasil - @kmanasil
Rohit Hemaraja- @Rohit-Hemaraja
Utkarsha Patil- @utkarshapatil01

- Describe the goal of the project.

Create a recommendation system to aid buyers in selecting the perfect pair of shoes

- Describe the data used or collected.

1. The data is from Kaggle and contains information about a variety of shoes from two different manufacturers.
2. It contains over 3 thousand observations but only just over 1500 unique products.
3. The data dictionary is well defined and easy to understand

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

1. They will do preprocessing and an EDA which is a good first step.
2. They will follow this with basic data visualization to demonstrate trends and patterns in the data
4. The plan from here is to create features, split the data for testing and evaluate the model - however you mention sentiment analysis but only seem to have numeric data in connection to customer reviews

- Is there anything that is unclear from the proposal?

1. Unsure how the research question can be answered without the actual reviews of the customers or the customers past shopping experiences (data)
2. Unsure of how a recommendation system can be done without individual consumer data

- Provide constructive feedback on how the team might be able to improve their project.

1. The research question it too vague and needs to be better defined
2. In order to build a recommendation system, you will need to expand the data to have individual consumer metrics
3. In order to do a sentiment analysis you may need to get individual consumer reviews, currently you only have the number of reviews.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

We really liked the Title and the abstract. They grab the attention right away.

- Provide constructive feedback on any issues with file and/or code organization.

We found it well organized and have no recommendations to improve this

- (Optional) Any further comments or feedback?

**Comment by partha-pkp** [comment]
Thanks for the review!
