### ISSUE TITLE
Code peer review

### ISSUE THREAD

**Issue by kmanasil** [INFO-523-Exercises/project-final-MineCrafters#5]
The following is the peer review of the project code by [name of team completing peer review]. The team members that participated in this review are 

[Kristi Manasil] - @[kmanasil]
[Dong Chen] - @[dongchen18]
[Utkarsha Patil] - @utkarshapatil01
[Anajani Sowmya Bollapragada] - @[asbollapragada]
[Rohit Hemaraja] - @Rohit-Hemaraja
---

#### 1. Purpose of Code
- [ ] Clearly defined and understood
- [ ]No
- [ X] Ambiguous or unclear
- Well each section is well defined, the overall notebook is difficult to navigate. Multiple notebooks might be easier to follow.

---

#### 2. Code Quality

- [ ] Code is clean, readable, and well-organized
 Yes it is organized but it is hard to interpret.
- [ ] Adequate comments explaining complex or tricky code sections
No, more information would be helpful to understand the features used in the models and the models performance. Graphs are not well explained or labeled.
- [X ] Variables, methods, and classes have meaningful names - Yes
- [ X] Consistent code style (indentation, naming conventions, etc.) - code style is consistent

---

#### 3. Documentation

- [ ] Code documentation (e.g., comments) is sufficient
No, more documentation explaining the process and the outputs is needed. There is also no to little documentation about why certain models were selected.
- [X ] Readme or other documentation updated if necessary - This seems to be something that is currently being worked on

---

#### 4. Best Practices

- [X ] No hardcoded values; constants used appropriately
- [X ] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [X] Code avoids repetition and promotes reusability
All of these seem good
---

#### 5. Additional Comments

- You need explain the process more, why models were selected, what the graphs or visualize are telling us, and what the output of models is saying/predicting. There seems to be little data transformation and more explanation may be needed here.
---

#### 6. Recommendation

- [ ] Approved - ready to be merged
- [X] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by Kevin-diesel-1194** [comment]
Thank you for your feedback, we will integrate these into our final project.
