### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by eshaanmathakari** [INFO-523-Exercises/project-final-MineCrafters#7]
The following is the peer review of the Presentation proposal by **Feature Finders Club**. The team members that participated in this review are 

Eshaan Mathakari - @eshaanmathakari

Sanjay Bhargav Siddi - @sanjaybhargavsiddi

Likith Kumar Dundigalla - @LikithKumarDundigalla

Aravind shrenivas Murali - @Aravind-shrenivas

Vamsi Vadala - @Vamsi-Vadala

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes, content was well designed and a lot of plots were used to show the results for project. Content related to the question was legible and data was accurately used.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes, they did. But, for some plots, the interpretation was not correct. We feel you could have included more different plots but the current ones represented the data well too.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
The project is carefully thought out and stuff. The limitations were considered and problems related to dataset were dealt with.
We would like to add one point that the presentation could be more visually comprehendable for someone with no previous scientific knowhow.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
Yes, slides are well arranged and creative layout on slides. Legends and titles were legible and different color themes were used. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
Yes, the presentation was good. All topics were covered by peers in the group .

**Comment by Kevin-diesel-1194** [comment]
Thank you Feature Finders Club for your feedback, we will take these suggestions into account and implement them in our future presentations.
