### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by kmanasil** [INFO-523-Exercises/project-final-MineCrafters#8]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

[Kristi Manasil] - @[kmanasil]

[Anjani Sowmya Bollapragada] - @[asbollapragada]

[Utkarsha Patil] - @[utkarshapatil01]

[Rohith Hemaraja] - @[rohith-hemaraja]

- ...

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes the question and data were nicely connected.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes while some labels were small they gave good explanations of the images.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
- While the team did mention that they ended up changing their project, they did seem to do a decent analysis in a short time frame.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
Some labels were a little small and some slides seemed text heavy.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
- They ran way over the time allowed, and one presenter stood in front of the slides and often had their back to the audience and made it hard to see/hear what he was saying.

**Comment by Kevin-diesel-1194** [comment]
Thank you Null Wranglers for your valuable feedback, we will correct our mistakes and implement them in future presentations.
